version: 0.2

phases:
  install:
      - pip install boto3    
  pre_build:
    commands:
      - echo "Checking out code..."
  build:
    commands:
      - python build_mapping.py
      - echo "Copying files to S3..."
      
  post_build:
    commands:
      - echo "Copying files to destination 1"      
artifacts:
    files:
      - '**/*'