version: 0.2

phases:
  install:
    commands:
      - echo "Install boto3"     
      - pip install boto3    
  pre_build:
    commands:
      - echo "Checking out code..."
      - echo $CODEBUILD_SRC_DIR
      - mkdir $CODEBUILD_SRC_DIR/buildoutput
  build:
    commands:
      - python build_mapping.py
      - echo "Copying files to S3..."
      
  post_build:
    commands:
      - echo "Copying files to destination 1"      
artifacts:
    files:
      - '**/*'