version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking out code..."

  build:
    commands:
      - echo "Copying files to S3..."
      
  post_build:
    commands:
      - echo "Copying files to destination 1"
      - echo "Source directory: ${CODEBUILD_SOURCE_DIR}"
      - echo "Artifact directory: ${CODEBUILD_ARTIFACTS_DIR}"
artifacts:
    files:
      - '**/*'